### ISSUE TITLE
Probleme with template 

### ISSUE THREAD

**Issue by arthur5640** [pibooth/pibooth-picture-template#12]
good morning.
I can't put a template that I created.
it tells me an error when processing the photo.
I created an .xml file which I copied to the config folder of pibooth.
when I put the classic template file everything works.

**Comment by werdeil** [comment]
Hi @arthur5640, can you provide some logs or the template you are using for us to see what is unexpected with it?

**Comment by arthur5640** [comment]
Bonjour .
J'ai un peu réglé le problème mais une chose me pose soucis 
Est ce possible sur un schéma (4 photos et 1 photo) d'avoir pour les 4 photos ( avec pluging template, pas doverlay mais un fond ) et pour le schéma 1 photo ( un overlay mais pas de fond) ? Je n'y arrive pas. Comme si on ne pouvait pas mettre en même temps u  fond et un overlay

**Comment by anxuae** [comment]
Not handled for the moment

**Comment by anxuae** [comment]
Will be possible in the next version

**Comment by anxuae** [comment]
v1.1.0 released
