### ISSUE TITLE
Creating template with designs

### ISSUE THREAD

**Issue by alexj47** [pibooth/pibooth-picture-template#13]
Hello, I tried to create a template in Flowchart Maker and inserted a .png file as background (see image attached). However, when I try to use the .xml as template in Pibooth, instead of listing the found templates, it gives me an error message with "too many values to unpack (expected 2)". What am I doing wrong and what do I need to do to add images as backgrounds in my templates? Thanks in advance.

<img width="446" alt="Bildschirmfoto 2022-06-30 um 17 10 19" src="https://user-images.githubusercontent.com/84335202/176712753-0d3e92d2-2b53-46f0-8408-2f4ebea8d2a7.png">
d

**Comment by werdeil** [comment]
Hi @alexj47, you shall separate the background part (which is done directly through pibooth options) from the template which only handle the layout.

**Comment by anxuae** [comment]
will be possible in the next version

**Comment by anxuae** [comment]
v1.1.0 released
