### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by JoostNuyttens** [pibooth/pibooth-picture-template#16]
Hello, sorry for asking another stupid question.  My photobooth finally works the way it should work except that I don't succeed to change the picture template at the end.  I succeeded in changing it using the plugin "pibooth picture template" saved it under EllaSimon2.xml.  According to the info on the screen all should be OK except that the final pictures are not put together using that template.  It looks like photobooth is using  'TemplatePictureFactory' as a template I think?  Any suggestion??

logging file: 

[ INFO    ] pibooth           : Initialize Google Photos connection
[ INFO    ] pibooth           : Show picture choice (4 captures selected)
[ INFO    ] pibooth           : Show preview before next capture
[ INFO    ] pibooth           : Take a capture
[ INFO    ] pibooth           : Show preview before next capture
[ INFO    ] pibooth           : Take a capture
[ INFO    ] pibooth           : Show preview before next capture
[ INFO    ] pibooth           : Take a capture
[ INFO    ] pibooth           : Show preview before next capture
[ INFO    ] pibooth           : Take a capture
[ INFO    ] pibooth           : Saving raw captures
[ INFO    ] pibooth           : Creating the final picture
[ INFO    ] pibooth           : Parsing pictures template file: /home/pb/Downloads/EllaSimon2.xml
[ INFO    ] pibooth           : Found template 'Page-1': 1 captures - 2 texts
[ INFO    ] pibooth           : Found template 'Page-2': 2 captures - 2 texts
[ INFO    ] pibooth           : Found template 'Page-3': 3 captures - 2 texts
[ INFO    ] pibooth           : Found template 'Page-4': 4 captures - 2 texts
[ INFO    ] pibooth           : Found template 'Page-5': 1 captures - 2 texts
[ INFO    ] pibooth           : Found template 'Page-6': 2 captures - 2 texts
[ INFO    ] pibooth           : Found template 'Page-7': 3 captures - 2 texts
[ INFO    ] pibooth           : Found template 'Page-8': 4 captures - 2 texts
[ INFO    ] pibooth           : Use TemplatePictureFactory to create background
[ INFO    ] pibooth           : Use TemplatePictureFactory to concatenate images
[ INFO    ] pibooth           : Use TemplatePictureFactory to assemble final image
[ INFO    ] pibooth           : Use TemplatePictureFactory to draw texts
[ INFO    ] pibooth           : Save image '/media/pb/PHOTOBOOTH/EllaSimon/2022-08-07-21-57-23_pibooth.jpg'
[ INFO    ] pibooth           : Found existing Google Photos album 'pibooth'

thanks for any help...

regards,

Joost

**Comment by anxuae** [comment]
Hi @JoostNuyttens 

Everything seems ok looking at the logs. Why do you think that there is an issue? Can you explain what do you expect?

(By the the way, I think you have created the issue at the wrong place. I will move it)

**Comment by JoostNuyttens** [comment]
Good morning,using the (existing) template I modified to 'EllaSimon2.xml'.  I used another font in the template and also the layout of the pictures is not the same.  The font is installed on the raspberry pi and can be used over there without any problem (so the installation of the font should be OK)

**Comment by werdeil** [comment]
Ok so you issue is that you get the correct layout but not the correct font? For fonts pibooth looks directly in the settings and do not use the template, see https://pibooth.readthedocs.io/en/latest/sources/start.html#texts-and-fonts
