### ISSUE TITLE
Template using images multiple times does not work

### ISSUE THREAD

**Issue by ammonshepherd** [pibooth/pibooth-picture-template#17]
I am trying to make a template for a classical style photobooth output; 2 or three images stacked on each other (like here: https://github.com/pibooth/pibooth-picture-template#user-content-step-5-add-new-a-template)

I have a template (the file is named "two") for two images, each used twice (so exactly like in the example linked above), but when I run `pibooth-regen` to test the template, I get the INFO line

`INFO:pibooth:Found template 'two': 4 captures - 4 texts`

And the error line

`pibooth_picture_template.TemplateParserError: No template for '2' captures (orientation=portrait)`

You can see the contents of the xml file below.

[two_pics.drawio.txt](https://github.com/pibooth/pibooth-picture-template/files/9759299/two_pics.drawio.txt)

My pibooth config is below

[pibooth_10_11_22.txt](https://github.com/pibooth/pibooth-picture-template/files/9759309/pibooth_10_11_22.txt)

How do I get pibooth to create the image with two captures duplicated?

**Comment by saboret73** [comment]
Hola, al final has encontrado solución?? A mi me ocurre lo mismo

**Comment by anxuae** [comment]
Hello I'm not able to open your file [two_pics.drawio.txt](https://github.com/pibooth/pibooth-picture-template/files/9759299/two_pics.drawio.txt) using [draw.io](https://www.draw.io/index.html).

"Unknown index" error appears.

**Comment by ammonshepherd** [comment]
[two_pics.drawio.txt](https://github.com/pibooth/pibooth-picture-template/files/9872920/two_pics.drawio.txt)

Here's an updated file with the index error fixed. I was able to open this version.

**Comment by anxuae** [comment]
Can you give me the complete log file with the crash ? I'm not able to reproduce your error

**Comment by saboret73** [comment]
hola, a mi me pasa el mismo problema, no puedo hacer tiras con fotos repetidas..

**Comment by anxuae** [comment]
Hi,

No new since a long time. This feature should work now.

Please reopen if you still have trouble.
