### ISSUE TITLE
What to place in Config ?

### ISSUE THREAD

**Issue by Tabata975** [pibooth/pibooth-picture-template#2]
Hello

I feel confused about what to change into the configuration  file after installation. 

It is written to add 
template = picture_template.xml on the Picture section

But where afterward is done the final choice, e.g. to activate the new template fancy.xml ?

**Comment by anxuae** [comment]
Hi @Tabata975 

You don't need to select a template.

As explained in the README (maybe unclear), the `fancy` template is the default installed.
It means that the file `picture_template.xml` generated at first startup will contain the template that I named `fancy`.

If it is more explicit for you, you can change the config like that:
```
template = fancy.xml
```

but if fact, the following line is also correct and do exactly the same thing (the content of the file will be the `fancy` template)

```
template = foo.xml
```

**Comment by Tabata975** [comment]
Thanks for the answer.
But then , if i do create my own template, i should place its name in the config ? 

An, btw, big thanks for what you share. I'm installing it since few days and amaized by Pibooth and such addons

**Comment by anxuae** [comment]
Yes, you can keep all your template files in the config folder, then change the key `template` with the correct file name.
At startup, if the file exists, `pibooth` will not override it, so your changes will be kept.

> An, btw, big thanks for what you share. I'm installing it since few days and amaized by Pibooth and such addons

Thanks a lot ;-)

**Comment by Tabata975** [comment]
Thanks again for the fast answer.
When all fully running, will also contibute on templates ;-)
