### ISSUE TITLE
Customiser template avec image ou theme

### ISSUE THREAD

**Issue by guigui91** [pibooth/pibooth-picture-template#3]
Bonjour je vois dans votre presentation que l'ont peut organiser les images mais est il possible de mettre des themes, images de fond ou autres????

Merci de votre aide et bravo pour votre travail

**Comment by anxuae** [comment]
Hello @guigui91 

(I'm switching in English for the community)

Use the standard options `[PICTURE][backgrounds]` and `[PICTURE][overlays]` to add background or overlay.
Templates are only for positioning elements.
