### ISSUE TITLE
Error when adding an image to the template

### ISSUE THREAD

**Issue by AndPDale** [pibooth/pibooth-picture-template#6]
Hi,
I am looking to add a static image to the resulting template. The image will be the same on every resulting photo array.

I have created the template in draw.io and imported it into Pibooth. I have regenerated the images (pibooth-regen) but I am seeing the following error message:  
"pibooth_picture_template.TemplateParserError: Too many captures positions (5) in template 'Page-1' (1 to 4 expected)"

I have included the xml I am using as a TXT file
[photograph.txt](https://github.com/pibooth/pibooth-picture-template/files/7358132/photograph.txt)

**Comment by anxuae** [comment]
Hi, you can't include images in the template, templates are only for captures place holder.

For static image, use `background` or `overlays` keys in the config
