### ISSUE TITLE
Can't use one raw image twice on template 

### ISSUE THREAD

**Issue by golere** [pibooth/pibooth-picture-template#8]
Hallo,
I'm copying my issue from https://github.com/pibooth/pibooth/issues/309 to here because it probably is a problem of the plugin.

Hallo everyone,

first I want to thank you all for this open-source software I'm very happy to use it for my first hobby Photobooth.

I want to print one image with 3 different photos each one should be appear twice on the template.

When using the example template everything is fine, also when I edit it a bit. As soon as I duplicate the placeholders and try to use the template I get the error:

`No template for '6' captures`

Because pibooth thinks I have 6 placeholders in the xml-file - eventhouth I only have 3 different placeholders duplicated ( 1-2-3 and 1-2-3).

Is there a workaround to get 1 capture twice on one processed image?

Thank you in advance!

**Comment by anxuae** [comment]
Hi @golere ,

No for the moment this feature is not supported.
But if you want to duplicate your photo, you can use the option in the config file:

```ini
# Print 1, 2, 3 or 4 picture copies per page
pictures_per_page = 2
```

**Comment by 0xecute** [comment]
Possible with this PR:
https://github.com/pibooth/pibooth-picture-template/pull/11
